blank_issues_enabled: false
contact_links:
  - name: MyVencord Support Server
    url: https://discord.gg/tdBCvjt7
    about: If you need help regarding MyVencord, please join our support server!
  - name: MyVencord Installer
    url: https://github.com/MyVencord/Installer
    about: You can find the MyVencord Installer here
